public enum TutorialStepType
{
	GoToHotspot = 1,
	StartBattle,
	EnterCamp,
	BuyWorldShopOffer,
	OpenChest,
	ExitWorldShop,
	Harvest,
	GoToHotspotOrCamp,
	BattleRule,
	PointOutNextHotspot,
	LeaveClassManager,
	EnteredBattle = 100,
	EnteredBattleWave,
	DefeatPig,
	AttackPig,
	SupportSelf,
	SupportOther,
	TapAndHold,
	UseConsumable,
	UseRage,
	ClickWheel,
	EnterConsumableBar,
	RerollBattle,
	FinishedBattle,
	DefeatPvPOpponent,
	ClickCampProp = 200,
	ClickFriendList = 204,
	EquipItem,
	CraftItem,
	CraftPotion = 203,
	RollGacha = 207,
	ClickNPCFriend,
	SelectRecipe,
	EquipItemFromCraftingResult,
	ExitCrafting,
	EnterShopCategory,
	BuyShopOffer,
	LeaveShop,
	UseGacha,
	ClickCampBird,
	SelectItem,
	ExitBirdManager,
	SelectCategory,
	LeaveGachaResult,
	ReadGachaTooltip,
	RerollCrafting,
	InputName,
	PvPReadDailyObjectives,
	PvPClickFightButton,
	PvPStartBattle,
	EnterEnchantment,
	AddResources,
	EnchantFirstItem,
	SelectBirdManagerCategory,
	SelectEnchantmentResource,
	ClickCampBirdWithSkin,
	SelectClassWithSkins,
	SwapSkin,
	EquipSkin,
	SkinEntryPoint,
	LeaveShopOrSkip,
	ChangeClassInBps,
	LeaveCamp
}
